[project]
name = "q5-mcp"
version = "0.1.0"
description = "Q5 MCP Classes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.13.1",
    "uvicorn>=0.35.0",
]
